version: "3"

services:

  core:
    image: "core:dev"
    container_name: "core"
    build:
      context: "./apps/core"
    networks:
      - "frontend"
      - "backend"
      - "userdomain"
    expose:
      - "50051"
    depends_on:
      - "user-database"
      - "cache-service"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  gateway:
    image: "gateway:dev"
    container_name: "gateway"
    build:
      context: "./apps/gateway"
    networks:
      - "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - "cache-service"
      - "core"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "localhost:3000/healthz -q -O - > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  payment:
    image: "payment:dev"
    container_name: "payment"
    build:
      context: "./plugins/payment"
    networks:
      - "frontend"
      - "backend"
    expose:
      - "50052"
    depends_on:
      - "core"
      - "cache-service"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "localhost:3002/healthz -q -O - > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  core-database:
    image: "postgres:latest"
    container_name: "core-database"
    networks:
      - "userdomain"
    expose:
      - "5432"
    volumes:
      - userdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME}'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

  cache-service:
    image: "redis:latest"
    container_name: "cache-service"
    networks:
      - "frontend"
      - "backend"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

networks:
  frontend:
  backend:
  userdomain:

volumes:
  userdata:
